services:
  - type: web
    name: florish-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn florishsavings.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: florishsavings.settings
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY
      - key: ALLOWED_HOSTS
        value: https://florishapp.onrender.com/N
