# Generated by Django 5.2.4 on 2025-07-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(choices=[('AGBOLI', 'agboli'), ('BIG_CHURCH', 'big_church'), ('SMART_ROAD', 'smart_road'), ('DO_GOOD', 'do_good'), ('FIKO_ROAD', 'fiko_road')], default='AG', max_length=200)),
                ('gender', models.CharField(choices=[('ML', 'male'), ('FE', 'female')], max_length=100)),
                ('business', models.CharField(max_length=200)),
                ('edited_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DL', 'daily'), ('WL', 'weekly'), ('ML', 'monthly')], default='DL', max_length=200)),
                ('amount', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('customer', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='savingapp.customer')),
            ],
        ),
    ]
