# Generated by Django 5.2.4 on 2025-07-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contributions',
            new_name='contribution',
        ),
    ]
