# Generated by Django 5.2.4 on 2025-07-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersaving',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customersaving',
            name='saving_plan',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='CustomerSaving',
        ),
        migrations.DeleteModel(
            name='SavingPlan',
        ),
    ]
