# Generated by Django 5.2.4 on 2025-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingapp', '0002_remove_customersaving_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
    ]
