# Generated by Django 5.2.4 on 2025-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingapp', '0002_rename_contributions_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='name',
            field=models.CharField(default='Mr Something', help_text='name of saving', max_length=100),
        ),
    ]
