# Generated by Django 5.2.4 on 2025-07-12 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingapp', '0003_contribution_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='edited_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('AGBOLI', 'agboli'), ('BIG CHURCH', 'big_church'), ('SMART ROAD', 'smart_road'), ('DO GOOD', 'do_good'), ('FIKO ROAD', 'fiko_road')], default='AG', max_length=200),
        ),
    ]
